### PR TITLE
shard status can be "resume" & explicitly defining shard statuses

### PR DESCRIPTION
**Pull request by DonovanDMC**

### CODE REVIEW

**Comment by DonovanDMC** [comment]
I feel like changing `status` to `state` would make more sense, when I think of "status", I think online/idle/dnd/offline. When I think of state, I think of disconnected/resuming/ready, etc.

**Comment by Brayzure** [comment]
I don't think changing `status` to `state` is the right idea here. The change is minor at best, while at the same time would be a breaking change for anyone who uses that property.

**Review by Brayzure — CHANGES_REQUESTED** [review]
Should revert the property name change for now. It's breaking for anyone who uses the property, and it kinda goes outside of the scope of the PR.

**Comment by apacheli** [comment]
@Brayzure it's been 2 months and this PR hasn't been edited. OP also opened another PR like a week ago, so clearly they don't really care about the breaking change.

**Comment by DonovanDMC** [comment]
Just because something doesn't get touched for a while, doesn't mean people don't care about it

**Comment by LJNeon** [comment]
When a change is requested and nothing is done for months, then work is done by the same person elsewhere, I would assume as much. Also, do you plan on making the requested changes? Your comment doesn't make that clear.

**Comment by Brayzure** [comment]
I asked you about this on Discord two weeks ago, and didn't get a response. I'd rather not have PRs in limbo for two months.

**Comment by DonovanDMC** [comment]
I don't see mentions from those servers as I have them shrouded in folders. As far as the "out of scope" bit goes, I agree, that was out of scope for this pull request.

**Comment by abalabahaha** [comment]
Still needs to undo the `status` to `state` breaking change

**Review by Brayzure — APPROVED** [review]

**Pull request merged**
