### PR TITLE
Fix GUILD_CREATE event

### PR DESCRIPTION
**Pull request by reinacchi**
`guildAvailable` should emit before the client turns ready

### CODE REVIEW

**Comment by bsian03** [comment]
This is intentional, the guild doesn't become unavailable then available again when a bot logs onto the gateway and as such would be a misleading report

**Comment by reinacchi** [comment]
The issue is that guildAvailable event doesn't get fired at all although it was called.

**Comment by bsian03** [comment]
In what case would it do that? The logic seems fine

**Comment by reinacchi** [comment]
tbh I'm not that really sure yet

**Pull request closed without merging**
