### PR TITLE
Update Discord URL

### PR DESCRIPTION
**Pull request by LJNeon**
Discord has changed their URL from `discordapp.com` to `discord.com`. However, this change does not apply to the CDN URL (`cdn.discordapp.com`).

### CODE REVIEW

**Comment by userterminal** [comment]
Was just about to change this

**Comment by alula** [comment]
What about ability to set a custom API base URL at this point for cases such as using it with Litecord/Mooncord/any similar thing?

**Comment by LJNeon** [comment]
Seems like I forgot to reply, but that does seem like a good idea. There are some other use cases for it like people who want to use v6 of the API instead of v7.

**Comment by exoRift** [comment]
How come they didn't change their CDN URL?

**Comment by abalabahaha** [comment]
[They don't want to](https://cdn.discordapp.com/attachments/381886868708655104/706949338042990662/unknown.png)

**Review by tbnritzdoge — APPROVED** [review]

**Review by tbnritzdoge — APPROVED** [review]
is good

**Review by Vetlix — APPROVED** [review]

**Comment by Brayzure** [comment]
>What about ability to set a custom API base URL at this point for cases such as using it with Litecord/Mooncord/any similar thing?

Interesting idea, but probably belongs in its own PR.

**Review by abalabahaha — APPROVED** [review]

**Pull request merged**
