### PR TITLE
add npm indicator and dependencies indicator

### PR DESCRIPTION
**Pull request by nandub**

### CODE REVIEW

**Comment by nandub** [comment]
I just notice, I forgot to point to the dev branch.  Let me know if you want me to change it.

**Comment by eritbh** [comment]
Minor thing: Having no space between the two badges makes it look weird.

**Comment by abalabahaha** [comment]
I believe the NPM URL on dev is already fixed...

Yeah a space between the badges would be nice.

**Comment by nandub** [comment]
Ok, I guess since it was moved to dev branch now I need to fix the conflicts.  Give me a sec to fix it.

**Comment by nandub** [comment]
Done rebase branch with dev and now we are good.

**Comment by eritbh** [comment]
Feel free to ignore this but now the space is inside the link so when you hover over it there's this little blue underline that appears out of nowhere.

**Comment by nandub** [comment]
@Geo1088 thanks, that is very annoying.  My mistake I put it in the wrong place.  Hold on.

**Comment by nandub** [comment]
second or third time is the charm.  try now.

**Comment by eritbh** [comment]
lol, looking good now. 👍

**Comment by abalabahaha** [comment]
👀

**Pull request merged**
