### PR TITLE
feat(Locales): add discord supported locales

### PR DESCRIPTION
**Pull request by YetAnotherConnor**
Added list of [discord supported locales](https://discord.com/developers/docs/reference#locales) to help localization typings.

I am unsure if there is any modifications needed to the jsdocs

### CODE REVIEW

**Review by bsian03 — CHANGES_REQUESTED** [review]
Please create a type alias for the locales constant

**Review by bsian03 — CHANGES_REQUESTED** [review]
Kinda surprised locales aren't in alphabetical order on discord docs.. would love for them to be organised here though (by ISO 639)

**Comment by bsian03** [comment]
you ordered them by name, not by iso639-1

**Comment by YetAnotherConnor** [comment]
My apologies, the ISO 639 list I found was ordered by the English key. I have now ordered the locales by their value

**Review by bsian03 — APPROVED** [review]

**Pull request merged**
