### PR TITLE
typo(InteractionCreateMessage)

### PR DESCRIPTION
**Pull request by flav-code**

### CODE REVIEW

**Comment by DonovanDMC** [comment]
initial response returns void

**Comment by flav-code** [comment]
And if you defer it returns the message

**Comment by DonovanDMC** [comment]
I'm aware
the point is that isn't a typo, it's intentional
You should take a look at every other interaction class

**Comment by flav-code** [comment]
I saw that the other interactiosn have the same,
If worst comes to worst, I'll create my own function createMessageAfterDefer(): Promise<Message>

**Comment by DonovanDMC** [comment]
have you considered createFollowup

**Comment by flav-code** [comment]
My bad...

I always thought that the createFollowup created a new message, but actually if there is no message yet the followup edit the message

Thanks we can close this

**Pull request closed without merging**
