### PR TITLE
getChannel/getRESTChannel/getGuildChannels generic

### PR DESCRIPTION
**Pull request by DonovanDMC**

### CODE REVIEW

**Comment by bsian03** [comment]
I feel like type asserting would be preferable instead of handling generics

**Comment by DonovanDMC** [comment]
being able to do `<Client>.getChannel<Eris.TextChannel>("").createMessage()` instead of `(<Client>.getChannel("") as Eris.TextChannel).createMessage()` is easier and looks nicer, in my opinion

**Comment by bsian03** [comment]
Or you can do `<TextableChannel>client.getChannel("")` which does the same thing

See [here](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions) for info

**Comment by DonovanDMC** [comment]
I know that one exists, but 
a.) most typescript projects (I've seen at least) enforce `as`
b.) that looks a bit ugly

**Comment by DonovanDMC** [comment]
Discussed in Discord, disregarded due to lib consistency.

**Pull request closed without merging**
