### PR TITLE
add: Message.createReply

### PR DESCRIPTION
**Pull request by arthur-rl**
Creates a reply to a message that mentions the author of the message.
```js
        message.createReply("This is a reply!")
```
img

### CODE REVIEW

**Comment by ghost** [comment]
Why?

**Comment by arthur-rl** [comment]
> 
> 
> Why?

why not?

**Comment by ghost** [comment]
because you don't... just add random stuff to a library for no reason? if you want it in your fork, that's fine, but it has no place in the library, at least in my opinion

**Comment by arthur-rl** [comment]
> 
> 
> because you don't... just add random stuff to a library for no reason? if you want it in your fork, that's fine, but it has no place in the library, at least in my opinion

I mean it's quite useful. otherwise you'll have to do 
```js
message.channel.createMessage(`<@${message.author.id}> blah`)
```
In my opinion its easier
```js
message.createReply("blah")
```

**Comment by Snazzah** [comment]
There is really no need for a change that is just prepending a mention to a message. Just because D.JS does it doesn't make it needed here.

**Comment by DonovanDMC** [comment]
Eris isn't meant to hold your hand with a lot of things. You can implement this yourself on your side by either editing the code, or adding it to the Message prototype.
```ts
Object.defineProperty(Eris.Message.prototype, "reply", {
	value: async function(content) {
		return this.channel.createMessage(`<@!${this.author.id}>, ${content}`);
	}
});
```

I haven't fully tested this, but it should work. You will need to do a lot more to support what the normal createMessage supports (i.e. embeds, allowMentions, files, etc...)

**Comment by arthur-rl** [comment]
> 
> 
> Eris isn't meant to hold your hand with a lot of things. You can implement this yourself on your side by either editing the code, or adding it to the Message prototype.
> 
> ```ts
> Object.defineProperty(Eris.Message.prototype, "reply", {
> 	value: async function(content) {
> 		return this.channel.createMessage(`<@!${this.author.id}>, ${content}`);
> 	}
> });
> ```
> 
> I haven't fully tested this, but it should work. You will need to do a lot more to support what the normal createMessage supports (i.e. embeds, allowMentions, files, etc...)

Thanks. I will add this to my code. closing the PR now.

**Pull request closed without merging**
