### PR TITLE
Update documentation for options.auth

### PR DESCRIPTION
**Pull request by Khaaz**
Webhooks now by default can use all emoji if the everyone role has the use external emojis permission. This can be safely removed

### CODE REVIEW

**Comment by bsian03** [comment]
Tbh I'd leave this in case someone removes use external emojis but still wants the webhook to use emojis that a specific bot has access to

**Comment by ghost** [comment]
Bot permissions have no effect on webhook emojis, even if the request is authorized with the bot token.

**Comment by Khaaz** [comment]
Yeah as said above, it's a (potentially unintentional) discord feature that have been removed entirely

**Comment by Khaaz** [comment]
as suggested by evan, we might want to actually keep this feature for larger scale bot that still want to auth with the bot token when sending request to discord.
This PR just precise the documentation.

**Review by abalabahaha — APPROVED** [review]

**Pull request merged**
