### PR TITLE
add certified moderator flag

### PR DESCRIPTION
**Pull request by untuned**
https://github.com/Discord-Datamining/Discord-Datamining/commit/6258cfefc7dde95d7c340397e9704c30da9a6280#commitcomment-50961513

### CODE REVIEW

**Comment by bsian03** [comment]
Is this actually exposed in v6/7?

**Comment by DonovanDMC** [comment]
I don't think they've given it out yet, but I don't see why it wouldn't be
it's not near high enough to cause any issues, and new flags appearing out of thin air (usually) won't break anything

**Comment by untuned** [comment]
> I don't think they've given it out yet, but I don't see why it wouldn't be
> it's not near high enough to cause any issues, and new flags appearing out of thin air (usually) won't break anything

It was recently added to canary, and supposedly it's for all members in the Discord Moderator Discord.

**Comment by DonovanDMC** [comment]
While we're on flags, can we talk about the naming of `VERIFIED_BOT_DEVELOPER`? That name is outdated, as [the docs](https://discord.com/developers/docs/resources/user#user-object-user-flags) call it `EARLY_VERIFIED_BOT_DEVELOPER`, because only early devs with the badge have the flag, so its old naming is a bit misleading

**Comment by untuned** [comment]
> While we're on flags, can we talk about the naming of `VERIFIED_BOT_DEVELOPER`? That name is outdated, as [the docs](https://discord.com/developers/docs/resources/user#user-object-user-flags) call it `EARLY_VERIFIED_BOT_DEVELOPER`, because only early devs with the badge have the flag, so its old naming is a bit misleading

Is that what the string is named?

**Comment by coolcalcacol** [comment]
> > While we're on flags, can we talk about the naming of `VERIFIED_BOT_DEVELOPER`? That name is outdated, as [the docs](https://discord.com/developers/docs/resources/user#user-object-user-flags) call it `EARLY_VERIFIED_BOT_DEVELOPER`, because only early devs with the badge have the flag, so its old naming is a bit misleading
> 
> Is that what the string is named?

Yup, at least according to this: https://discord.com/developers/docs/resources/user#user-object-user-flags

**Comment by HeadTriXz** [comment]
Also, `DISCORD_PARTNER` is no longer used either. It got replaced with `PARTNERED_SERVER_OWNER`.

**Comment by DonovanDMC** [comment]
> Also, `DISCORD_PARTNER` is no longer used either. It got replaced with `PARTNERED_SERVER_OWNER`.

I didn't even notice that one

**Comment by untuned** [comment]
With the [official announcement](https://blog.discord.com/announcing-our-latest-profile-badge-the-certified-discord-moderator-908182193af8) on their blog, I believe this should be merged. It has also been added to the [user flags list](https://discord.com/developers/docs/resources/user#user-object-user-flags) in the Discord developer documentation, in commit https://github.com/discord/discord-api-docs/commit/55cd3d71082e9dc31cbd007a6e74b1cd6a82beeb.

listed on a user profile

**Review by bsian03 — APPROVED** [review]
Name changes can be in its own PR (it's also in the v9 PR but if someone wants to do it before then, feel free)

**Pull request merged**
