### PR TITLE
Make things a bit more clear

### PR DESCRIPTION
**Pull request by HenryMachin**

### CODE REVIEW

**Comment by ray-1337** [comment]
There is no official confirmation from the library owner (abalabahaha) that this package is/was discontinued.

**Review by Scraayp — CHANGES_REQUESTED** [review]
There is no official confirmation from the library owner (abalabahaha) that this package is/was discontinued.

**Review by MDCYT — APPROVED** [review]

**Review by DonovanDMC — APPROVED** [review]

**Review by doomestee — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by HeadTriXz — APPROVED** [review]

**Comment by DonovanDMC** [comment]
Creeper

**Comment by HeadTriXz** [comment]
Aww man

**Comment by MertBhey** [comment]
So we back in the mine

**Comment by DonovanDMC** [comment]
got our pickaxe swinging from side to side

**Comment by MertBhey** [comment]
Side-side to side

**Comment by NotCallMeHacker** [comment]
This task, a grueling one

**Comment by HeadTriXz** [comment]
Hope to find some diamonds tonight, night, night

**Comment by NotCallMeHacker** [comment]
Diamonds tonight

**Comment by HeadTriXz** [comment]
Heads up

**Comment by NotCallMeHacker** [comment]
You hear a sound, turn around and look up

**Comment by DonovanDMC** [comment]
total shock fills your body

**Comment by HeadTriXz** [comment]
Oh, no. It's you again

**Comment by NotCallMeHacker** [comment]
I can never forget those eyes, eyes, eyes

**Comment by HeadTriXz** [comment]
Eyes, eyes, eyes

**Comment by DonovanDMC** [comment]
Eyes-eye-eyes

**Comment by DonovanDMC** [comment]
'Cause baby tonight

**Comment by NotCallMeHacker** [comment]
The creeper's trying to steal all our stuff again

**Comment by HeadTriXz** [comment]
'Cause baby tonight

**Comment by NotCallMeHacker** [comment]
Grab your pick, shovel, and bolt again

**Comment by DonovanDMC** [comment]
And run, run until it's done, done

**Comment by MertBhey** [comment]
And run, run until it's done, done

**Comment by HeadTriXz** [comment]
Until the sun comes up in the morn'

**Comment by MertBhey** [comment]
'Cause, baby, tonight

**Comment by HeadTriXz** [comment]
The creeper's trying to steal all our stuff again

**Comment by MertBhey** [comment]
Just when you think you're safe

**Comment by HeadTriXz** [comment]
Overhear some hissing from right behind

**Comment by abalabahaha** [comment]
Notice will be posted when the time comes

**Pull request closed without merging**
