### PR TITLE
Added functions to allow voice channel leave without channelID (and fixed some related things)

### PR DESCRIPTION
**Pull request by TheAkio**
The title says it all. Newly added functions are Client.prototype.leaveVoiceGuild(guildID) and Guild.prototype.leaveVoiceChannel(). Functionality has been tested and TypeScript typings were also added. Feel free to adjust the function names as I was not 100% sure how to call them.

### CODE REVIEW

**Comment by abalabahaha** [comment]
Needs a better name than `leaveVoiceGuild()` lol

**Comment by TheAkio** [comment]
No shit sherlock. I still need one, idk how to call that lol

**Comment by TheAkio** [comment]
Some naming ideas:

leaveGuildVoice()
leaveVoiceConnection()
closeVoiceConnection()
killVoiceConnection()

All not very nice but maybe it helps.

**Comment by alula** [comment]
`closeVoiceConnection()` is a better name for it.

**Comment by TheAkio** [comment]
Also fixed the 2 things we mentioned eariler in DAPI about leaveVoiceChannel() having a useless getChannel() call and the "Cannot read property channels of undefined" error. Functionality has been tested.

**Pull request merged**
