### PR TITLE
update Member.js

### PR DESCRIPTION
**Pull request by attributeerror**
Added two new getters: tag and highestRole
tag will return the user's username and discriminator combined (e.g. AttributeError#2513)
highestRole will return the member's highest role in the server, or null if they don't have any roles.

### CODE REVIEW

**Comment by TTtie** [comment]
Here are multiple issues with your code:

1. Your code doesn't comply with the eslint rules that are set for this repo
2. Your highestRole implementation doesn't even work
3. These methods can be easily implemented as utility methods for your bot.

If you'd like something more beginner friendly, please check out discord.js instead.

I recommend you to close this PR now, because it is probably going to be closed anyway.

Thanks,
TTtie.

**Comment by attributeerror** [comment]
1) I just ran it through a checker and there were no issues, so I would like to see where you checked the code.
2) I ran multiple of my own checks, on different members, in different servers, and it worked perfectly every time, so I'd also like to see how you checked the code.
3) I'm aware, these started as utility methods but I felt like other people could find them useful - is there anything wrong with helping the community?

Last time I checked, Eris is far more beginner-friendly than Discord.js, and when I've recommended both D.JS and Eris to actual beginners, they've chosen Eris and stuck with it.

I appreciate your concern, but I'll wait for the owner of the repo to close the PR. Thank you.

**Comment by knht** [comment]
Just wanted to make sure that you know that's not how actual tests work. Throwing something together beneficial to yourself and testing it on a few instances isn't covering merely enough test cases. 

Also, Eris has always striven to stick very closely to the API Discord provides. This change isn't part of it. Eris has never aimed to be a high level abstraction like Discord.js.

**Comment by eritbh** [comment]
As far as the checker you ran it through, it must not have been checking eslint rules. Missing semicolon in User.js

**Comment by attributeerror** [comment]
I wasn't aware that was Eris' aim - I've always seen it as a smaller library that has created way after D.JS and didn't yet have some of the more useful features, such as the two I added here.

As for the eslint checks, not sure what happened with that but I'll fix it when I get back on my computer.

Thank you both for the *constructive* criticism.

**Comment by LJNeon** [comment]
For relevant discussion on why `Member#tag` won't be accepted into the lib, see #252. The same will very likely apply to `Member.highestRole`

**Comment by abalabahaha** [comment]
Partial duplicate of #252. As people may have mentioned, Eris doesn't really include higher-level helpers like these. Leans closer to being simple and lower-level than to being beginner-friendly/batteries-included.

Also, some improvements: `sort()` wants `a - b` instead of `a < b`. It's also relatively inefficient compared to a `max()`-like implementation, since we only need the single highest object.

**Pull request closed without merging**
