### PR TITLE
Add clyde

### PR DESCRIPTION
**Pull request by itslukej**
important for normal operation of every discord bot

### CODE REVIEW

**Review by wrightk — APPROVED** [review]

**Comment by abalabahaha** [comment]
Clyde has no ID

**Review by minemidnight — COMMENTED** [review]
I believe we need this.

**Comment by Mstrodl** [comment]
yes I agree

**Review by julien777z — COMMENTED** [review]
good work

**Comment by Thewsomeguy** [comment]
If you get a Clyde msg and mention `<@1>` it mentions Clyde, so Clyde has an id of 1.

**Comment by julien777z** [comment]
Please merge this PR or my bot will never be complete

**Comment by abalabahaha** [comment]
It's not possible to get a Clyde message in a library. Add this to your own bot if you want.

Locked due to brigading.

**Pull request closed without merging**
