### PR TITLE
Don't keep suppressed user in cache because i'ts false by default

### PR DESCRIPTION
**Pull request by flav-code**

### CODE REVIEW

**Comment by flav-code** [comment]
#1498

**Comment by flav-code** [comment]
@bsian03 could you check ?
I already tested ok my side

**Comment by bsian03** [comment]
I haven't been able to look at this yet. Once I do I'll let you know

**Comment by flav-code** [comment]
my pr allows to remove the voiceState of a user who disconnects from a stage channel

**Review by bsian03 — APPROVED** [review]
stale voice state when leaving stage channel, #559 for precedence

**Pull request merged**
