### PR TITLE
Allow lib files to be imported directly

### PR DESCRIPTION
**Pull request by ghost**
this pr removes gluten from all brands of eris bread

### CODE REVIEW

**Comment by exoRift** [comment]
What does this do, exactly?

**Comment by Androz2091** [comment]
nothing I think

**Comment by bsian03** [comment]
> What does this do, exactly?

Does what it says on the tin. Gotta cater for those who have special dietary requirements!

**Comment by eritbh** [comment]
It appears to allow consumers to import any eris file individually, rather than being limited to the listed entry points ([Reference in node docs](https://nodejs.org/api/esm.html#esm_package_entry_points )) I'm not sure why this change is necessary or what's motivating it.

Edit: the original addition of the exports list prevented people from importing anything from files at all, which can break things for people using eris in bundled environments, and this PR fixes that by allowing any file to be imported from eris (with the caveat that file extensions are required).

**Review by abalabahaha — APPROVED** [review]

**Pull request merged**
