### PR TITLE
Fix status

### PR DESCRIPTION
**Pull request by reinacchi**
`"offline"` doesn't exist instead it should be `"invisible"`.

### CODE REVIEW

**Comment by Dramex** [comment]
According to discord api docs it's `offline` not `invisable`

source: 
https://discord.dev/topics/gateway#presence-update-presence-update-event-fields

**Comment by DonovanDMC** [comment]
As far as the gateway is concerned, offline and invisible are the same thing
docs say `offline`, so it should be `offline`

**Comment by reinacchi** [comment]
`Client.editStatus("offline")` won't change bots status to fully offline, this is why I made this pr since it works when `offline` is replaced with `invisible` and that's what is written down in the [Eris Docs](https://abal.moe/Eris/docs/Client#method-editStatus)

I had already checked in the Discord API docs if the gateway expects `offline` and not `invisible` but as said, I'm making this pr to fix `Client#editStatus` as `offline` doesn't affect bots status, it'll still remain online.

**Comment by bsian03** [comment]
I'll allow the extra type for `invisible`, but not completely replace `offline`. Setting a status to `offline` and it not working should be reported as a bug/outdated documentation to the API repo.

I'll also mark PR as draft until this is clarified.

**Comment by DonovanDMC** [comment]
According to the docs, [both invisible and offline exists](https://discord.com/developers/docs/topics/gateway#update-presence-status-types) (mistake on my part), so invisible should be added, not replacing offline

**Comment by bsian03** [comment]
> According to discord api docs it's `offline` not `invisable`

You're looking at the wrong location, that's for gateway presence update event, not Update presence command

**Comment by Dramex** [comment]
> > According to discord api docs it's `offline` not `invisable`
> 
> You're looking at the wrong location, that's for gateway presence update event, not Update presence command

Apologize thoguht this PR for presence update🤦‍♂️, then in this case yes invisible replaces offline.

**Comment by reinacchi** [comment]
> According to the docs, [both invisible and offline exists](https://discord.com/developers/docs/topics/gateway#update-presence-status-types) (mistake on my part), so invisible should be added, not replacing offline

You're right. Just checked on that recently. But since afaik that `offline` can only be received, and `invisible` can only be sent through the gateway, does `invisible` still need to be added or replaced fully by `offline`?

**Comment by bsian03** [comment]
Refer to my earlier comment.

**Comment by bsian03** [comment]
Can we separate invisble and offline types and use them in their relevant references

**Review by bsian03 — APPROVED** [review]

**Pull request merged**
