### PR TITLE
Update typings (cbd4674, 206480c, b3ff9b3, 1d55807, 7eace2a)

### PR DESCRIPTION
**Pull request by aurieh**
Most notable changes:
* (a5db43aa9578ba8eae33c1de65b733f99b37a00c) Part 1 update is mostly just class changes
* (e8254545dc9e2e3f7f9041b37ecaa4fe16b6b721) Part 2 ensures backwards-compat w/ older code
* (684b3a7c4cd734538bf28612562bb74d8d556e14) Part 3 adds Invitable and moves invite methods to that

Other commits are just generic prop updates for other commits

Requesting a review from @noud02 and @LJNeon

### CODE REVIEW

**Comment by na-2n** [comment]
👌

**Comment by LJNeon** [comment]
`getMessageReaction` needs a `before` param added as well as the `after` param.

**Comment by LJNeon** [comment]
Other than that looks all good to me.

**Comment by aurieh** [comment]
@LJNeon 745b6feebd739573ba7a6117909b3f444d9f700f should be it

**Comment by LJNeon** [comment]
@aurieh 👌

**Pull request merged**
