### PR TITLE
Fix avatar update

### PR DESCRIPTION
**Pull request by MergHQ**
The base64 header was missing. Thanks to Aurieh#8140 for finding this bug :100:

### CODE REVIEW

**Comment by hsiW** [comment]
This never really was a bug, you were just required to do it yourself.

**Comment by MergHQ** [comment]
Ahh okay. Maybe it's still a good idea since Buffer.toString('base64') returns only the data and not the header?

**Comment by hayleyxyz** [comment]
This explicitly hardcodes the mime type as image/jpeg, which will not be the case of all images.

**Comment by hsiW** [comment]
_thats why part of why it was closed_

**Pull request closed without merging**
