### PR TITLE
Typescript typings (#237)

### PR DESCRIPTION
**Pull request by aurieh**
Features:
* Allows proper autocompletion when using VSCode intellisense and JS/TS LSP
* Allows library usage in TypeScript projects without type guessing
🙏

### CODE REVIEW

**Review by TTtie — COMMENTED** [review]
:thinking: This should be optional IMO, I know it is always present in a message embed object but people omit it when sending embed messages.

Talking about line 19.

**Comment by aurieh** [comment]
@TTtie I might separate it and some other type aliases (like EmojiOptions), as properties differ when sending and receiving data.

**Comment by TTtie** [comment]
👌

**Comment by cryptiklemur** [comment]
Is this easy enough to update every time abal updates something @aurieh? Is this automateable?

**Comment by abalabahaha** [comment]
There are plans for integrating this into the docs generator but its manual for now. The API isn't changing much anyway

**Comment by cryptiklemur** [comment]
👍 lets merge then :D

**Comment by aurieh** [comment]
@aequasi @abalabahaha
It's really easy to add methods and props to definitions file.
About generating definitions, it's possible but fairly hard.
Take [Microsoft/dts-gen](https://github.com/Microsoft/dts-gen) as an example. Definitions it generates are lacking as it can't infer properties like a human can.
Along with that, even if you were to make something that works well, current documentation would be hard to work with, as some types and props are missing or are just `Object`. With webhook payload types, you can redirect users to discord api developer docs, but a generator can't infer what properties it should have.
What I'm saying is that it's only possible to write quality definition files by hand.

**Pull request merged**
