### PR TITLE
Added a pre-defined endpoint list for directly using API endpoints.

### PR DESCRIPTION
**Pull request by amirfarzamnia**
This update introduces a pre-defined list of API endpoints to Eris, simplifying the detection of each feature's endpoint URL and associated request method. This enhancement streamlines the process for bot developers who need to send API requests directly, making it more straightforward and efficient.

### CODE REVIEW

**Comment by bsian03** [comment]
What's the use case? Can you message me on the server about this?

**Comment by MCausc78** [comment]
> What's the use case? Can you message me on the server about this?

Most likely [undocumented] features that Eris does not support, such as sending REMIX'ed attachments, clips, setting pronouns, etc

**Comment by amirfarzamnia** [comment]
> What's the use case? Can you message me on the server about this?

I'll message you on the Discord server.

**Comment by amirfarzamnia** [comment]
This PR is still in progress; more details are provided on the Discord server.

**Pull request closed without merging**
