### PR TITLE
Interactions MinMax

### PR DESCRIPTION
**Pull request by JustCat80**
Interactions min and max value options for Int and Number

Also fixed some typings, removes required for Sub command things, and adds focused

Adds AnyInteraction

### CODE REVIEW

**Comment by DonovanDMC** [comment]
Suggestion for an `AnyInteraction` type that's a union of all of the interaction types (excluding unknown)
useful for types

**Comment by JustCat80** [comment]
so just
`type AnyInteraction: PingInteraction | CommandInteraction | ComponentInteraction | AutocompleteInteraction`
?

**Comment by DonovanDMC** [comment]
> so just `type AnyInteraction: PingInteraction | CommandInteraction | ComponentInteraction | AutocompleteInteraction` ?

type * = but yes

**Comment by DonovanDMC** [comment]
I'm also pretty sure the `data.type` of AutocompleteInteraction should only be 1

**Comment by DonovanDMC** [comment]
since Message/User Apps don't take arguments, they can't use autocomplete, so it should be impossible for them to be there

**Comment by DonovanDMC** [comment]
pretty sure the top level `data.options` will always be present for autocomplete interactions since we need to know what field we're responding to

**Review by abalabahaha — APPROVED** [review]
@DonovanDMC says it's fine

**Pull request merged**
