### PR TITLE
fix(slash): Snake case defaultPermissions to payload

### PR DESCRIPTION
**Pull request by bsian03**

### CODE REVIEW

**Comment by coolcalcacol** [comment]
I thought this was in another PR @bsian03?

**Comment by DonovanDMC** [comment]
I left it as snake case as most things around interactions is already snake case

**Comment by bsian03** [comment]
Did the PR with the intention that it would be merged first - Donovan's PR would also technically cause a breaking change from the docs perspective

**Comment by DonovanDMC** [comment]
I'll just take it out of my pr, since this will almost certainly make it in first, and that is true

**Review by See887777 — APPROVED** [review]

**Review by DonovanDMC — APPROVED** [review]

**Review by curtisf — APPROVED** [review]

**Pull request merged**
