### PR TITLE
Fix broken ratelimiter

### PR DESCRIPTION
**Pull request by ak-s**
- timeOffset must be positive if local clock is behind (see [#L197](https://github.com/abalabahaha/eris/blob/dev/lib/rest/RequestHandler.js#L197)).
offset = serverTime - clientTime
reset = serverResetTime - offset
serverResetTime == serverTime + resetAfter
So for reactions: reset = clientTime + resetAfter (compatibility in case of disabled millisecond precision).
Reset calculations broken since 2017, how no one noticed?
- retryAfter >= 0 is true if retryAfter === null [#L257](https://github.com/abalabahaha/eris/blob/dev/lib/rest/RequestHandler.js#L257)
Just leave it as a possible NaN after parseInt.

### CODE REVIEW

**Comment by abalabahaha** [comment]
Why was the reactions override offset removed?

**Comment by ak-s** [comment]
Because timeOffset is needed to adjust server time, not local.
clientTime + resetAfter ==> serverTime - offset + resetAfter ==> serverResetTime - offset

I think about adding half a second to headerNow in timeOffset calculation
`const timeOffset = headerNow + 500 - (this.latencyRef.lastTimeOffsetCheck = Date.now());`
to increase accuracy, what do you say?

**Comment by abalabahaha** [comment]
TBH this was more of a failed experiment from a long time ago to see if we could cheat by sending requests early so that they arrive at Discord closer to the ratelimit reset time. But yeah I guess the resolution of the Date header is worse than the reaction ratelimit.

+500 does sound theoretically better, does it change things much in practice?

**Comment by ak-s** [comment]
This may be significant for large bots. Just need some testing to make sure there is no 429 error.

**Comment by ak-s** [comment]
At first everything worked fine, but after a day I got a few 429 errors caused by a rounding error.

**Review by abalabahaha — APPROVED** [review]

**Pull request merged**
