### PR TITLE
Guild missing properties

### LINKED ISSUE #1079: Discovery splash not implemented
Guilds have a relatively new `discovery_splash` attribute in the [Discord docs](https://discord.com/developers/docs/resources/guild#guild-object-guild-structure) which is not implemented in Eris.

### PR DESCRIPTION
**Pull request by cyclane**
- Added `discoverySplash`, `discoverySplashURL`, `dynamicDiscoverySplashURL`, `systemChannelFlags` attributes to Guild.
- Added `discoverySplashURL` attribute to GuildPreview.
- Added `discoverySplash`, `widgetEnabled`, `widgetChannelID`, `maxMembers`, `vanityURL`, `premiumTier`, `premiumSubscriptionCount`, `maxVideoChannelUsers` attributes to OldGuild.

Closes #1079

### CODE REVIEW

**Comment by bsian03** [comment]
Just mention they're needed in #1033, no point duplicating a PR

**Comment by cyclane** [comment]
> Just mention they're needed in #1033, no point duplicating a PR

Okay, I've mentioned it, it's just that PR seems specifically for the edit function but if it does get implemented I'll close this one

**Comment by bsian03** [comment]
Right sorry that's mb, been working far too long, ignore me

**Comment by cyclane** [comment]
I changed the name of this PR since I found another missing property `system_channel_flags` in the [Discord API](https://discord.com/developers/docs/resources/guild#guild-object-guild-structure) so the name of the source branch is kinda inaccurate, but that shouldn't matter too much

**Comment by Khaaz** [comment]
system channel flag is part of #1067 already

**Comment by Khaaz** [comment]
I also +1 bsian since I apprently already made a PR for that, although I seem to have forgot half of it, so be free to add it directly in there or I'll do it when I get time to fix my PRs

**Comment by cyclane** [comment]
> system channel flag is part of #1067 already

Oh sorry, thank you for pointing that out, I removed the changes related to system channels.

> I also +1 bsian since I apprently already made a PR for that, although I seem to have forgot half of it, so be free to add it directly in there or I'll do it when I get time to fix my PRs

I'll close this PR once these additions are added to #1033, just to make sure they are added one way or another.

**Comment by cyclane** [comment]
I found a bunch of attributes that were missing on OldGuild which I also put in this PR, so I think at this point we might as well keep #1033 and this separate. (that is unless the attributes that I thought were missing, are meant to be missing for some reason?)

**Comment by Khaaz** [comment]
after a second look, my PR aimed specifically to fix an inconsistency in editGuild. You can keep your PR as it is. Both will work together anyway. The final point is that we should have discoverySplash everywhere so it's fine

**Review by abalabahaha — APPROVED** [review]

**Pull request merged**
