### PR TITLE
VoiceState returns a class with id when not in voice channel;

### PR DESCRIPTION
**Pull request by TTtie**
use channelID property instead

### CODE REVIEW

**Comment by SapphoSys** [comment]
noice 10/10

**Comment by matix2267** [comment]
Can't we instead add a property voiceState.isConnected or something like that?

**Comment by hsiW** [comment]
why .-.

**Comment by matix2267** [comment]
IMO it's better to check `voiceState.isConnected` (if it's `true` or `false`) than to check something like `if(voiceState.channelID !== null)` if you want to see if a user is connected to voice channel or not.

Or maybe not, dunno, I'm ok with either way, but I would change the line in the example to `if(msg.member.voiceState.channelID !== null)` instead of the current `if(!msg.member.voiceState.channelID)`

**Comment by TTtie** [comment]
@matix2267 well, `VoiceState.channelID` is something like that too, also `VoiceState.channelID` will be undefined when not in a voice channel, so that's why `if(!msg.member.voiceState.channelID)`; we check if it is undefined.

**Comment by TTtie** [comment]
^ also, where's [`VoiceState.isConnected`](https://github.com/abalabahaha/eris/blob/dev/lib/structures/VoiceState.js)

**Comment by matix2267** [comment]
There isn't, I just asked if it couldn't be added, but it's more of a design issue and that is up to the library owner to decide. My subjective opinion is that `if(msg.member.voiceState.isConnected)` has the clearest meaning, next is `if(msg.member.voiceState.channelID !== null)` which I suggested in previous comment if we don't want to add another field to `VoiceState`, and then `if(!msg.member.voiceState.channelID)` is the most obscure because you can very easily miss `!`. Anyway, I'm just adding my 2 cents here, it's no big deal whatever you choose will be fine, it's just a matter of code style / examples.

**Comment by abalabahaha** [comment]
I believe the line of reasoning is that if you're not in a voice channel (missing voiceState.channelID), you're probably not connected to a voice channel.

Feel free to open another PR/issue if you think this behavior should be changed.

**Pull request merged**
