### PR TITLE
Create a latency command example! 

### PR DESCRIPTION
**Pull request by CanasDev**
One more example of what you can use with eris
An command to see the bot latency!

### CODE REVIEW

**Comment by CanasDev** [comment]
Lint fixed

**Comment by CanasDev** [comment]
bruh , the reason its autoexplicative.

**Comment by CanasDev** [comment]
*self-explanatory lol

**Comment by ray-1337** [comment]
what are you doing?

**Comment by coolcalcacol** [comment]
> what are you doing?

Making egg waffles atm, want a plate?

**Comment by d00mster0** [comment]
> > what are you doing?
> 
> Making egg waffles atm, want a plate?

Can I ask for one as well 😮

**Comment by FlyingFussl** [comment]
> > > what are you doing?
> > 
> > 
> > Making egg waffles atm, want a plate?
> 
> Can I ask for one as well 😮

Make an example command for posting an egg waffle picture, so people see you can send pictures with eris

**Pull request closed without merging**
